
const { retrieveFile } = require('./uri-retriever');
const { generatePackageJson } = require('./npm-search');
const crawler = require('./crawler');
const downloader = require('./downloader');
const generator = require('./generator');

/**
 * @description downloads the tarballs required by the specified package-lock.json file
 * @param {string} uri
 * @param {{ directory: string }} options
 */
async function packageLockCommand(uri, options = {}) {
  const packageLock = await retrieveFile(uri);
  downloader.downloadFromPackageLock(packageLock, options.directory);
}

/**
 * @description downloads the tarballs required by the specified package
 * @param {string} name
 * @param {string} version
 * @param {{ directory: string, devDependencies: boolean, peerDependencies: boolean }} options
 */
async function packageCommand(name, version, options = {}) {
  const tarballsSet = await crawler.getDependencies({
    name,
    version,
    devDependencies: options.devDependencies,
    peerDependencies: options.peerDependencies,
  });
  downloader.downloadFromIterable(tarballsSet, options.directory);
}

/**
 * @description downloads the tarballs required by the specified package.json file
 * @param {string} uri
 * @param {{ directory: string, devDependencies: boolean, peerDependencies: boolean }} options
 */
async function packageJsonCommand(uri, options = {}) {
  const packageJson = await retrieveFile(uri);
  const tarballsSet = await crawler.getPackageJsonDependencies({
    packageJson,
    devDependencies: options.devDependencies,
    peerDependencies: options.peerDependencies,
  });
  downloader.downloadFromIterable(tarballsSet, options.directory);
}

/**
 * @description downloads tarballs based on the search result of the npm registry
 * @param {string} keyword
 * @param {{ directory: string, devDependencies: boolean, peerDependencies: boolean }} options
 */
async function searchCommand(keyword, options = {}) {
  const packageJson = await generatePackageJson({ keyword });
  const tarballsSet = await crawler.getPackageJsonDependencies({
    packageJson,
    devDependencies: options.devDependencies,
    peerDependencies: options.peerDependencies,
  });
  downloader.downloadFromIterable(tarballsSet, options.directory);
}

/**
 * @description create a file with tarballs links that can used by the `fromGeneratedCommand` function to download the files
 * @param {string} keyword
 * @param {{ outputFile: string, devDependencies: boolean, peerDependencies: boolean }} options
 */
async function generateCommand(name, version, options) {
  const tarballsSet = await crawler.getDependencies({
    name,
    version,
    devDependencies: options.devDependencies,
    peerDependencies: options.peerDependencies
  });
  const defaultOutputFile = `${name}${version ? `-${version}` : ''}.generated`;
  generator.saveToFile(Array.from(tarballsSet), options.outputFile || defaultOutputFile);
}

/**
 * @description downloads tarballs based on a file generated by the `generateCommand` function
 * @param { string } uri 
 * @param {{ directory: string }} options 
 */
async function fromGeneratedCommand(uri, options) {
  const tarball = await generator.readFromFile(uri);
  downloader.downloadFromIterable(tarball, options.directory);
}

module.exports = {
  packageLockCommand,
  packageCommand,
  packageJsonCommand,
  searchCommand,
  generateCommand,
  fromGeneratedCommand
};
